// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfjgiokmdqxygmtdixag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmamdpb2ttZHF4eWdtdGRpeGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTAwNDAsImV4cCI6MjA2NzA4NjA0MH0.5mniCBfPyvWAatdMp29J752VsPDwzHlw-mHPUxXHsFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});